import random
import math
from datetime import datetime, timedelta
from collections import defaultdict

# ---- Configuration ---------------------------------------------------------
NUM_COMPANIES    = 5
NUM_USERS        = 20
NUM_TICKETS      = 30
SEED             = 42
START_DATE       = datetime(2024, 1, 1)
END_DATE         = datetime(2025, 3, 1)
# ---------------------------------------------------------------------------

random.seed(SEED)

INDUSTRIES   = ["Technology", "Finance", "Retail", "Healthcare", "Logistics", "Manufacturing"]
TIERS        = ["standard", "premium", "enterprise"]
DEPARTMENTS  = ["IT", "Engineering", "Finance", "Operations", "HR", "Sales", "Legal"]
PRIORITIES   = ["low", "medium", "high", "critical"]
CATEGORIES   = ["Network", "Email", "Hardware", "Access", "Software", "VPN"]

# ---- Helpers --------------------------------------------------------------

def rand_name():
    first = ["Alice", "Bob", "Carol", "Dan", "Eva", "Frank", "Grace", "Hank", "Iris", "Jake"]
    last = ["Smith", "Jones", "Patel", "Kim", "Chen", "Reyes", "Ng", "Torres"]
    return random.choice(first) + " " + random.choice(last)

def ts_str(dt):
    return "TO_TIMESTAMP('{0}', 'YYYY-MM-DD HH24:MI:SS')".format(dt.strftime('%Y-%m-%d %H:%M:%S'))

def date_str(dt):
    return "TO_DATE('{0}', 'YYYY-MM-DD')".format(dt.strftime('%Y-%m-%d'))

def escape_sql(s):
    return s.replace("'", "''")

# ---- Generation -----------------------------------------------------------

def generate():
    lines = []
    def emit(sql): lines.append(sql)

    emit("-- =============================================================")
    emit("-- generated_data.sql (Updated for Aggregate Snapshots)")
    emit("-- =============================================================")

    # 1. Companies
    company_ids = list(range(1, NUM_COMPANIES + 1))
    for i in company_ids:
        name = f"Company {i} " + random.choice(['Corp', 'Inc', 'LLC', 'Solutions'])
        emit("INSERT INTO companies (company_name, industry, tier) VALUES ('{0}', '{1}', '{2}');"
             .format(escape_sql(name), random.choice(INDUSTRIES), random.choice(TIERS)))

    # 2. Users
    tech_ids = [1, 2, 3]
    for uid in range(1, NUM_USERS + 1):
        role = "technician" if uid in tech_ids else "customer"
        emit("INSERT INTO users (company_id, full_name, email, role, department) VALUES ({0}, '{1}', 'user{2}@test.com', '{3}', '{4}');"
             .format(random.choice(company_ids), rand_name(), uid, role, random.choice(DEPARTMENTS)))

    # 3. Tickets Logic
    # We need to track data to aggregate for the snapshot table
    daily_stats = defaultdict(lambda: {"open": 0, "solved": 0, "durations": []})

    for tid in range(1, NUM_TICKETS + 1):
        cid = random.choice(company_ids)
        created_at = START_DATE + timedelta(days=random.randint(0, 300))
        day_key = (created_at.date(), cid)
        
        status = random.choice(["open", "in_progress", "resolved", "closed"])
        priority = random.choice(PRIORITIES)
        
        # Track stats for snapshots
        daily_stats[day_key]["open"] += 1
        if status in ["resolved", "closed"]:
            daily_stats[day_key]["solved"] += 1
            # Simulate a resolution time between 1 and 48 hours
            handle_time = round(random.uniform(1, 48), 2)
            daily_stats[day_key]["durations"].append(handle_time)

        emit("INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) "
             "VALUES ({0}, {1}, {2}, 'Issue {3}', 'Description', '{4}', '{5}', '{6}', {7});"
             .format(cid, random.randint(4, NUM_USERS), random.choice(tech_ids), tid, priority, status, random.choice(CATEGORIES), ts_str(created_at)))

    emit("\n-- Ticket Daily Snapshots (Aggregated by Date and Company)")
    # 4. Snapshots (Matching your specific Table Structure)
    for (s_date, cid), stats in daily_stats.items():
        avg_time = round(sum(stats["durations"]) / len(stats["durations"]), 2) if stats["durations"] else 0
        
        emit("INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) "
             "VALUES (TO_DATE('{0}', 'YYYY-MM-DD'), {1}, {2}, {3}, {4});"
             .format(s_date, cid, stats["open"], stats["solved"], avg_time))

    emit("\nCOMMIT;")
    print("\n".join(lines))

if __name__ == "__main__":
    generate()
    def emit(sql):
        lines.append(sql)

    emit("-- =============================================================")
    emit("-- generated_data.sql  (auto-generated by Python script)")
    emit("-- Generated: {0}".format(datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
    emit("-- Config: {0} companies, {1} users, {2} tickets".format(
        NUM_COMPANIES, NUM_USERS, NUM_TICKETS))
    emit("-- =============================================================")
    emit("")

    # Companies
    emit("-- Companies")
    company_ids = []
    company_names = []
    used_names = set()
    for i in range(1, NUM_COMPANIES + 1):
        while True:
            name = random.choice(['Alpha', 'Beta', 'Gamma', 'Delta', 'Omega', 'Apex', 'Nova', 'Titan', 'Zenith', 'Crest']) + " " + \
                   random.choice(['Corp', 'Inc', 'LLC', 'Solutions', 'Group', 'Partners', 'Systems', 'Labs', 'Ventures', 'Co'])
            if name not in used_names:
                used_names.add(name)
                break
        industry = random.choice(INDUSTRIES)
        tier = random.choice(TIERS)
        company_ids.append(i)
        company_names.append(name)
        emit("INSERT INTO companies (company_name, industry, tier) VALUES ('{0}', '{1}', '{2}');".format(escape_sql(name), industry, tier))
    emit("")

    # Users
    emit("-- Users")
    user_ids, user_roles, user_companies, technician_ids = [], [], [], []
    used_emails = set()
    for uid in range(1, NUM_USERS + 1):
        company_id = random.choice(company_ids)
        domain = rand_domain(company_names[company_id - 1])
        name = rand_name()
        
        if uid <= max(2, int(NUM_USERS * 0.15)):
            role = "technician"
            technician_ids.append(uid)
        else:
            role = "customer"

        email = rand_email(name, domain)
        if email in used_emails:
            email = email.replace("@", f"{uid}@")
        used_emails.add(email)

        user_ids.append(uid)
        user_roles.append(role)
        user_companies.append(company_id)
        emit("INSERT INTO users (company_id, full_name, email, role, department) VALUES ({0}, '{1}', '{2}', '{3}', '{4}');"
             .format(company_id, escape_sql(name), email, role, random.choice(DEPARTMENTS)))
    emit("")

    # Tickets
    emit("-- Tickets")
    ticket_data = []
    customer_ids = [u for u, r in zip(user_ids, user_roles) if r == "customer"] or user_ids

    for tid in range(1, NUM_TICKETS + 1):
        company_id = random.choice(company_ids)
        submitter = random.choice(customer_ids)
        priority = random.choice(PRIORITIES)
        category = random.choice(CATEGORIES)
        created_at = rand_ts(START_DATE, END_DATE)
        
        r = random.random()
        status = "open"
        assigned_to = "NULL"
        resolved_at = None

        if r > 0.15:
            status = random.choice(["in_progress", "resolved", "closed"])
            assigned_to = str(random.choice(technician_ids))
            if status in ["resolved", "closed"]:
                resolved_at = created_at + timedelta(hours=resolution_hours(priority))

        subject = f"{random.choice(['Issue with', 'Request for'])} {category.lower()} {random.choice(['system', 'access'])}"
        desc = f"User reports {category.lower()} issue."
        
        ticket_data.append({"id": tid, "status": status, "priority": priority, "company_id": company_id, "created_at": created_at})
        
        res_sql = f", {ts_str(resolved_at)}" if resolved_at else ", NULL"
        emit(f"INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) "
             f"VALUES ({company_id}, {submitter}, {assigned_to}, '{escape_sql(subject)}', '{escape_sql(desc)}', '{priority}', '{status}', '{category}', {ts_str(created_at)}{res_sql});")
    emit("")

    # CSAT & Snapshots
    emit("-- CSAT Scores")
    for t in ticket_data:
        if t["status"] in ("resolved", "closed") and random.random() < 0.6:
            emit(f"INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES ({t['id']}, {random.choice(customer_ids)}, {csat_score()}, 'Generated feedback');")
    
    emit("\n-- Ticket Daily Snapshots")
    for t in ticket_data:
        emit(f"INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) "
             f"VALUES ({date_str(t['created_at'])}, {t['id']}, {t['company_id']}, '{t['status']}', '{t['priority']}', {round(random.uniform(0, 24), 2)}, 'N', {random.randint(0, 3)});")

    emit("\nCOMMIT;")
    print("\n".join(lines))

if __name__ == "__main__":
    generate()
