-- =============================================================
-- generated_data.sql  (auto-generated by Python script)
-- Generated: 2026-03-24 02:57:02
-- Config: 5 companies, 20 users, 30 tickets
-- =============================================================

-- Companies
INSERT INTO companies (company_name, industry, tier) VALUES ('Beta Corp', 'Logistics', 'standard');
INSERT INTO companies (company_name, industry, tier) VALUES ('Delta LLC', 'Finance', 'enterprise');
INSERT INTO companies (company_name, industry, tier) VALUES ('Beta Co', 'Education', 'standard');
INSERT INTO companies (company_name, industry, tier) VALUES ('Alpha Inc', 'Healthcare', 'standard');
INSERT INTO companies (company_name, industry, tier) VALUES ('Zenith Co', 'Technology', 'enterprise');

-- Users
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Wendy White', 'wendy.white@deltallc.com', 'technician', 'Operations');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Olivia Harris', 'olivia.harris@deltallc.com', 'technician', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Yara Reyes', 'yara.reyes@betacorp.com', 'technician', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (4, 'Karen Wu', 'karen.wu@alphainc.com', 'customer', 'Engineering');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Yara Lee', 'yara.lee@deltallc.com', 'customer', 'IT');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Mia Kim', 'mia.kim@betacorp.com', 'customer', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Tina Wu', 'tina.wu@betaco.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Xander Taylor', 'xander.taylor@betacorp.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Mia Patel', 'mia.patel@betacorp.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Uma Martin', 'uma.martin@betaco.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Sam Ng', 'sam.ng@betaco.com', 'customer', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Bob Torres', 'bob.torres@betacorp.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Carol Torres', 'carol.torres@betaco.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Mia Wu', 'mia.wu@betacorp.com', 'customer', 'Operations');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Frank Brown', 'frank.brown@betaco.com', 'customer', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Victor Wu', 'victor.wu@deltallc.com', 'customer', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Tina Reyes', 'tina.reyes@betacorp.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Frank Taylor', 'frank.taylor@deltallc.com', 'customer', 'Operations');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Uma White', 'uma.white@betaco.com', 'customer', 'Engineering');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Yara Jones', 'yara.jones@betaco.com', 'customer', 'Engineering');

-- Tickets
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (1, 14, 3, 'Request for software access', 'User reports software issue.', 'high', 'closed', 'Software', TO_TIMESTAMP('2024-02-21 09:50:42', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-21 23:15:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 12, 2, 'Issue with access system', 'User reports access issue.', 'medium', 'resolved', 'Access', TO_TIMESTAMP('2024-11-28 18:35:07', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-05 10:11:32', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 19, 2, 'Request for network access', 'User reports network issue.', 'low', 'closed', 'Network', TO_TIMESTAMP('2024-03-26 04:00:28', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-27 23:25:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 4, 1, 'Request for email system', 'User reports email issue.', 'critical', 'resolved', 'Email', TO_TIMESTAMP('2024-09-21 05:19:49', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-09-21 08:31:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 7, 3, 'Issue with software system', 'User reports software issue.', 'critical', 'in_progress', 'Software', TO_TIMESTAMP('2024-03-02 04:08:16', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (4, 9, 1, 'Issue with other system', 'User reports other issue.', 'medium', 'resolved', 'Other', TO_TIMESTAMP('2024-07-11 13:17:44', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-07-12 22:41:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (1, 5, 3, 'Issue with email access', 'User reports email issue.', 'medium', 'in_progress', 'Email', TO_TIMESTAMP('2024-01-25 09:34:47', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (4, 10, 1, 'Issue with hardware access', 'User reports hardware issue.', 'high', 'in_progress', 'Hardware', TO_TIMESTAMP('2025-01-02 08:51:16', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 17, 1, 'Issue with printing system', 'User reports printing issue.', 'high', 'in_progress', 'Printing', TO_TIMESTAMP('2024-03-17 10:38:31', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 18, 1, 'Request for vpn system', 'User reports vpn issue.', 'medium', 'in_progress', 'VPN', TO_TIMESTAMP('2024-05-22 12:27:53', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (1, 4, 2, 'Issue with access access', 'User reports access issue.', 'low', 'in_progress', 'Access', TO_TIMESTAMP('2024-11-07 11:55:58', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 18, 3, 'Issue with vpn access', 'User reports vpn issue.', 'medium', 'in_progress', 'VPN', TO_TIMESTAMP('2025-01-13 00:12:45', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (1, 5, 1, 'Issue with printing system', 'User reports printing issue.', 'high', 'in_progress', 'Printing', TO_TIMESTAMP('2025-02-16 12:54:31', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 16, 3, 'Request for access access', 'User reports access issue.', 'low', 'closed', 'Access', TO_TIMESTAMP('2024-11-21 14:55:07', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-24 06:48:15', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 14, 2, 'Issue with software access', 'User reports software issue.', 'medium', 'resolved', 'Software', TO_TIMESTAMP('2024-11-03 09:58:58', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-15 18:10:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 7, 2, 'Issue with other system', 'User reports other issue.', 'low', 'in_progress', 'Other', TO_TIMESTAMP('2024-06-14 13:29:03', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 13, 3, 'Issue with printing system', 'User reports printing issue.', 'medium', 'resolved', 'Printing', TO_TIMESTAMP('2025-02-14 20:10:09', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-02-15 20:29:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 7, 1, 'Request for other access', 'User reports other issue.', 'low', 'closed', 'Other', TO_TIMESTAMP('2024-04-30 17:45:32', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-05-04 01:22:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 5, 3, 'Request for vpn system', 'User reports vpn issue.', 'low', 'in_progress', 'VPN', TO_TIMESTAMP('2024-08-02 21:41:35', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (4, 17, 3, 'Issue with network access', 'User reports network issue.', 'high', 'in_progress', 'Network', TO_TIMESTAMP('2024-03-27 21:28:49', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 8, 2, 'Issue with hardware system', 'User reports hardware issue.', 'high', 'in_progress', 'Hardware', TO_TIMESTAMP('2024-02-02 11:44:47', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (1, 15, 1, 'Request for vpn access', 'User reports vpn issue.', 'high', 'in_progress', 'VPN', TO_TIMESTAMP('2024-05-17 12:29:43', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 12, 2, 'Request for email system', 'User reports email issue.', 'medium', 'resolved', 'Email', TO_TIMESTAMP('2024-12-31 14:17:52', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-01-01 22:28:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 4, 2, 'Request for access access', 'User reports access issue.', 'critical', 'in_progress', 'Access', TO_TIMESTAMP('2024-11-05 11:56:39', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 14, 1, 'Request for email access', 'User reports email issue.', 'low', 'resolved', 'Email', TO_TIMESTAMP('2024-07-21 21:24:15', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-07-29 19:19:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 20, 2, 'Issue with vpn system', 'User reports vpn issue.', 'low', 'closed', 'VPN', TO_TIMESTAMP('2024-05-27 15:19:30', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-06-03 12:11:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 17, 3, 'Request for authentication access', 'User reports authentication issue.', 'low', 'in_progress', 'Authentication', TO_TIMESTAMP('2024-10-21 11:46:48', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (5, 4, 2, 'Issue with software system', 'User reports software issue.', 'medium', 'closed', 'Software', TO_TIMESTAMP('2024-12-09 10:27:21', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-13 09:07:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (3, 20, 3, 'Request for authentication system', 'User reports authentication issue.', 'critical', 'in_progress', 'Authentication', TO_TIMESTAMP('2024-03-13 12:51:48', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at, resolved_at) VALUES (2, 8, 3, 'Issue with network access', 'User reports network issue.', 'low', 'closed', 'Network', TO_TIMESTAMP('2024-02-26 13:36:59', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-26 23:37:34', 'YYYY-MM-DD HH24:MI:SS'));

-- CSAT Scores
INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES (1, 11, 5, 'Generated feedback');
INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES (15, 20, 4, 'Generated feedback');
INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES (17, 7, 4, 'Generated feedback');
INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES (26, 18, 4, 'Generated feedback');
INSERT INTO csat_scores (ticket_id, rated_by, score, comments) VALUES (30, 18, 3, 'Generated feedback');

-- Ticket Daily Snapshots
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-02-21', 'YYYY-MM-DD'), 1, 1, 'closed', 'high', 17.85, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-11-28', 'YYYY-MM-DD'), 2, 2, 'resolved', 'medium', 10.8, 'N', 1);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-03-26', 'YYYY-MM-DD'), 3, 5, 'closed', 'low', 20.16, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-09-21', 'YYYY-MM-DD'), 4, 5, 'resolved', 'critical', 18.38, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-03-02', 'YYYY-MM-DD'), 5, 5, 'in_progress', 'critical', 15.04, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-07-11', 'YYYY-MM-DD'), 6, 4, 'resolved', 'medium', 10.56, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-01-25', 'YYYY-MM-DD'), 7, 1, 'in_progress', 'medium', 5.63, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2025-01-02', 'YYYY-MM-DD'), 8, 4, 'in_progress', 'high', 7.67, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-03-17', 'YYYY-MM-DD'), 9, 3, 'in_progress', 'high', 3.32, 'N', 1);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-05-22', 'YYYY-MM-DD'), 10, 5, 'in_progress', 'medium', 9.19, 'N', 1);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-11-07', 'YYYY-MM-DD'), 11, 1, 'in_progress', 'low', 16.95, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2025-01-13', 'YYYY-MM-DD'), 12, 3, 'in_progress', 'medium', 9.96, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2025-02-16', 'YYYY-MM-DD'), 13, 1, 'in_progress', 'high', 13.02, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-11-21', 'YYYY-MM-DD'), 14, 2, 'closed', 'low', 1.49, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-11-03', 'YYYY-MM-DD'), 15, 2, 'resolved', 'medium', 9.35, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-06-14', 'YYYY-MM-DD'), 16, 5, 'in_progress', 'low', 20.56, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2025-02-14', 'YYYY-MM-DD'), 17, 3, 'resolved', 'medium', 11.45, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-04-30', 'YYYY-MM-DD'), 18, 3, 'closed', 'low', 7.17, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-08-02', 'YYYY-MM-DD'), 19, 3, 'in_progress', 'low', 20.48, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-03-27', 'YYYY-MM-DD'), 20, 4, 'in_progress', 'high', 12.92, 'N', 1);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-02-02', 'YYYY-MM-DD'), 21, 5, 'in_progress', 'high', 11.72, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-05-17', 'YYYY-MM-DD'), 22, 1, 'in_progress', 'high', 10.46, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-12-31', 'YYYY-MM-DD'), 23, 2, 'resolved', 'medium', 9.33, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-11-05', 'YYYY-MM-DD'), 24, 2, 'in_progress', 'critical', 17.38, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-07-21', 'YYYY-MM-DD'), 25, 5, 'resolved', 'low', 22.07, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-05-27', 'YYYY-MM-DD'), 26, 5, 'closed', 'low', 21.77, 'N', 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-10-21', 'YYYY-MM-DD'), 27, 3, 'in_progress', 'low', 2.01, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-12-09', 'YYYY-MM-DD'), 28, 5, 'closed', 'medium', 3.26, 'N', 3);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-03-13', 'YYYY-MM-DD'), 29, 3, 'in_progress', 'critical', 4.36, 'N', 2);
INSERT INTO ticket_daily_snapshot (snapshot_date, ticket_id, company_id, status, priority, age_hours, is_over_sla, num_comments_to_date) VALUES (TO_DATE('2024-02-26', 'YYYY-MM-DD'), 30, 2, 'closed', 'low', 9.1, 'N', 1);

COMMIT;

=== Code Execution Successful ===
