-- =============================================================
-- generated_data.sql (Updated for Aggregate Snapshots)
-- =============================================================
INSERT INTO companies (company_name, industry, tier) VALUES ('Company 1 Corp', 'Technology', 'enterprise');
INSERT INTO companies (company_name, industry, tier) VALUES ('Company 2 LLC', 'Finance', 'standard');
INSERT INTO companies (company_name, industry, tier) VALUES ('Company 3 Inc', 'Manufacturing', 'standard');
INSERT INTO companies (company_name, industry, tier) VALUES ('Company 4 Corp', 'Logistics', 'premium');
INSERT INTO companies (company_name, industry, tier) VALUES ('Company 5 Corp', 'Technology', 'standard');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Dan Smith', 'user1@test.com', 'technician', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Iris Ng', 'user2@test.com', 'technician', 'Engineering');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (4, 'Jake Chen', 'user3@test.com', 'technician', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Carol Ng', 'user4@test.com', 'customer', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Carol Kim', 'user5@test.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Bob Jones', 'user6@test.com', 'customer', 'Operations');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Frank Reyes', 'user7@test.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Alice Torres', 'user8@test.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Grace Jones', 'user9@test.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Jake Reyes', 'user10@test.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Bob Smith', 'user11@test.com', 'customer', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Eva Jones', 'user12@test.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Bob Ng', 'user13@test.com', 'customer', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (4, 'Frank Patel', 'user14@test.com', 'customer', 'Finance');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Dan Chen', 'user15@test.com', 'customer', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Jake Patel', 'user16@test.com', 'customer', 'HR');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (2, 'Carol Torres', 'user17@test.com', 'customer', 'Operations');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Iris Kim', 'user18@test.com', 'customer', 'Sales');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (3, 'Alice Kim', 'user19@test.com', 'customer', 'Legal');
INSERT INTO users (company_id, full_name, email, role, department) VALUES (1, 'Frank Ng', 'user20@test.com', 'customer', 'Finance');
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 16, 3, 'Issue 1', 'Description', 'medium', 'resolved', 'Access', TO_TIMESTAMP('2024-04-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 12, 3, 'Issue 2', 'Description', 'medium', 'in_progress', 'Software', TO_TIMESTAMP('2024-05-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (4, 8, 3, 'Issue 3', 'Description', 'high', 'closed', 'Access', TO_TIMESTAMP('2024-10-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 9, 3, 'Issue 4', 'Description', 'medium', 'open', 'Access', TO_TIMESTAMP('2024-01-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (5, 18, 3, 'Issue 5', 'Description', 'critical', 'closed', 'Hardware', TO_TIMESTAMP('2024-02-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (5, 14, 1, 'Issue 6', 'Description', 'high', 'open', 'Hardware', TO_TIMESTAMP('2024-01-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (4, 12, 3, 'Issue 7', 'Description', 'low', 'closed', 'Email', TO_TIMESTAMP('2024-03-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (5, 9, 3, 'Issue 8', 'Description', 'medium', 'resolved', 'Software', TO_TIMESTAMP('2024-02-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 15, 2, 'Issue 9', 'Description', 'low', 'closed', 'Email', TO_TIMESTAMP('2024-06-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 19, 1, 'Issue 10', 'Description', 'low', 'open', 'Software', TO_TIMESTAMP('2024-05-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 17, 1, 'Issue 11', 'Description', 'medium', 'closed', 'Software', TO_TIMESTAMP('2024-03-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 20, 2, 'Issue 12', 'Description', 'high', 'closed', 'Network', TO_TIMESTAMP('2024-06-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 4, 3, 'Issue 13', 'Description', 'high', 'open', 'Software', TO_TIMESTAMP('2024-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 5, 1, 'Issue 14', 'Description', 'low', 'open', 'Network', TO_TIMESTAMP('2024-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 12, 3, 'Issue 15', 'Description', 'medium', 'open', 'Access', TO_TIMESTAMP('2024-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 11, 2, 'Issue 16', 'Description', 'critical', 'in_progress', 'Access', TO_TIMESTAMP('2024-10-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 15, 2, 'Issue 17', 'Description', 'critical', 'open', 'Access', TO_TIMESTAMP('2024-02-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (4, 16, 3, 'Issue 18', 'Description', 'low', 'open', 'Hardware', TO_TIMESTAMP('2024-01-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 18, 1, 'Issue 19', 'Description', 'medium', 'in_progress', 'Access', TO_TIMESTAMP('2024-05-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 6, 2, 'Issue 20', 'Description', 'medium', 'closed', 'Software', TO_TIMESTAMP('2024-05-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 11, 1, 'Issue 21', 'Description', 'low', 'open', 'Access', TO_TIMESTAMP('2024-01-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (4, 5, 1, 'Issue 22', 'Description', 'critical', 'in_progress', 'Access', TO_TIMESTAMP('2024-09-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 19, 1, 'Issue 23', 'Description', 'critical', 'resolved', 'Email', TO_TIMESTAMP('2024-07-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (3, 14, 1, 'Issue 24', 'Description', 'low', 'open', 'Network', TO_TIMESTAMP('2024-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (5, 20, 1, 'Issue 25', 'Description', 'low', 'in_progress', 'Email', TO_TIMESTAMP('2024-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (1, 7, 3, 'Issue 26', 'Description', 'critical', 'in_progress', 'Email', TO_TIMESTAMP('2024-02-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (5, 20, 2, 'Issue 27', 'Description', 'critical', 'open', 'Hardware', TO_TIMESTAMP('2024-01-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 16, 1, 'Issue 28', 'Description', 'high', 'in_progress', 'VPN', TO_TIMESTAMP('2024-06-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (3, 7, 1, 'Issue 29', 'Description', 'low', 'resolved', 'Software', TO_TIMESTAMP('2024-08-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO tickets (company_id, submitted_by, assigned_to, subject, description, priority, status, category, created_at) VALUES (2, 6, 1, 'Issue 30', 'Description', 'medium', 'resolved', 'Hardware', TO_TIMESTAMP('2024-09-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Ticket Daily Snapshots (Aggregated by Date and Company)
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-04-18', 'YYYY-MM-DD'), 1, 1, 1, 31.81);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-05-15', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-10-25', 'YYYY-MM-DD'), 4, 1, 1, 11.31);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-01-25', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-02-02', 'YYYY-MM-DD'), 5, 1, 1, 29.01);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-01-06', 'YYYY-MM-DD'), 5, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-03-21', 'YYYY-MM-DD'), 4, 1, 1, 45.83);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-02-24', 'YYYY-MM-DD'), 5, 1, 1, 8.18);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-06-14', 'YYYY-MM-DD'), 1, 1, 1, 6.26);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-05-03', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-03-06', 'YYYY-MM-DD'), 2, 1, 1, 13.46);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-06-08', 'YYYY-MM-DD'), 2, 1, 1, 21.59);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-04-25', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-04-22', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-06-18', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-10-03', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-02-18', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-01-28', 'YYYY-MM-DD'), 4, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-05-07', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-05-22', 'YYYY-MM-DD'), 2, 1, 1, 42.1);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-01-26', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-09-03', 'YYYY-MM-DD'), 4, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-07-18', 'YYYY-MM-DD'), 1, 1, 1, 14.41);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-04-21', 'YYYY-MM-DD'), 3, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-09-01', 'YYYY-MM-DD'), 5, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-02-04', 'YYYY-MM-DD'), 1, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-01-21', 'YYYY-MM-DD'), 5, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-06-09', 'YYYY-MM-DD'), 2, 1, 0, 0);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-08-22', 'YYYY-MM-DD'), 3, 1, 1, 1.44);
INSERT INTO ticket_daily_snapshot (snapshot_date, company_id, open_tickets, solved_today, avg_handle_time_hrs) VALUES (TO_DATE('2024-09-16', 'YYYY-MM-DD'), 2, 1, 1, 44.86);

COMMIT;

